version: '3.7'

services:
  middleware:
    build: 
      context: ./middleware
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 main:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
  frontend:
    container_name: frontend
    build:
      context: ./frontend/app
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'