version: '3.7'

services:
  middleware:
    build: 
      context: ./middleware
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 main:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend/app
      args:
        - NODE_ENV=development
      dockerfile: Dockerfile.prod
    ports:
      - 9000:9000
    depends_on:
      - middleware
  
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - middleware
      - frontend
    links:
      - middleware
      - frontend