version: '3.7'

services:
  middleware:
    build: ./middleware
    command: python main.py run -h 0.0.0.0
    volumes:
      - ./middleware/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./middleware/.flaskenv
  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    volumes:
      - './frontend/app:/usr/src/app'
      - 'usr/src/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    # depends_on:
    #   middleware:
    #     condition: service_started
    links:
      - middleware