version: '3.7'

services:
  web:
    build:
      context: ./middleware
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 main:app
    expose:
      - 5000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
#     depends_on:
#       - db
#   db:
#     image: postgres:12.0-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     env_file:
#       - ./.env.prod.db

# volumes:
#   postgres_data: